service: bookmyshow-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1


plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /ping
          method: GET
  pingWebhook:
    handler: handler.webhook
    events:
      - httpApi:
          path: /webhook
          method: POST
  remainderCron:
      handler: handler.cronToremainder
      timeout: 60
      events:
        - schedule: cron(*/2 * * * ? *)
  dailyCleanUpCron:
      handler: handler.dailyCleanUpCron
      timeout: 60
      events:
        - schedule: cron(0 0 * * ? *)
